FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# testdev

this is the contain of the web

# Group Posts

## Questions Collection [/questions]

### Get All Questions [GET/questions]

+ Response 200 (application/json)
    
    + Attributes 
        
        - questions (array[Questions])
        
# Data Structure 

## Questions (object)

+ id: 1 (number) - ID of the question
+ content: this is the question? (string) - Content of the question
+ author: admin (string) - Question author